---
deployment:
  tasks:
    - export DEPLOYPATH=/home/farmilos/public_html/isoinspector/
    - /bin/cp ./build/* $DEPLOYPATH
    - /bin/cp ./build/assets/* $DEPLOYPATH
    - /bin/cp ./build/ssr-build/* $DEPLOYPATH